### ISSUE TITLE
RFC: Operator API design

### ISSUE THREAD

**Issue by ryzhyk** [vmware/database-stream-processor#92]
## RFC: Operator API design (so far just a list of problems with the current design)

The current API for assembling operators into circuits has poor ergonomics.
This is partially because it is intentionally low-level, designed to support maximal
flexibility as opposed to ease of use, and partially because it was built in
a bottom-up fashion, with little consideration for user experience.
My goal is to cleanup the design where possible and also hide some low-level details
behind a less flexible but more user-friendly higher-level API.

Below is a summary of problems along with some ideas for addressing them, but first
I mention the aspects of the current design that work well and that I'd like to
preserve going forward.

## The good

- The functional style of instantiating operators, similar to DD, LINQ, and many other
  systems is nice compared to manually instantiating operators and connecting their
  outputs (the `stream.map().join().distinct()` stuff).

- The operator caching feature allows creating high-level operators without introducing
  a performance hit, e.g., `stream.distinct_trace()` internally calls `stream.trace()`.
  If another operator in the circuit calls `stream.trace()`, it will get a reference to
  the same trace rather than creating a new one.  

## The bad

1. **API requires type annotations.** Most operators are generic over return type, e.g.,
   happy to return any type that implements `trait ZSet`.  The goal is to support multiple
   ZSet implementations (e.g., in-memory and disk-backed), but the downside is that the
   programmer often needs to explicitly specify the return type using type annotations.
   - [x] Proposed solution: PR #94 

1. **Operator naming.**  Operator names are currently a complete mess.  Names like
   `join_trace` for example make zero sense to the user.  Ignoring the current lame naming
   scheme, a sensible naming convention is not easy to some up with because DBSP
   supports multiple flavors of the same operator.  Linear operators (map, filter, index,
   etc.) are easy, as the same implementation works in incremental and non-incremental cases
   and for arbitrary nesting depth.  `join`, `aggregate`, `distinct`, and other non-linear
   operators are more tricky.  First, they have incremental and non-incremental versions.
   We typically use the former in practice, but there are situations where non-incremental
   operators are useful.  Whether we use an `_incremental` suffix for incremental operators
   of `_non_incremental` (or something to that effect) for non-incremental operators, this
   will be easy to get wrong since the type system currently doesn't distinguish between
   streams of changes and streams that carry complete collections.  An additional complication
   is that some operators have incremental implementations specialized for different nesting
   depths.  The type system does not currently enforce the use of the correct implementation
   for the given scope.
   - [x] Proposed solution: PR #98 
 
1. **Trace-based API vs generic API.**  Operators like `integrate()`, `integrate_nested()`
   work for any values that form a group, but are inefficient when working with Z-sets and
   indexes Z-sets, which is what we care about 99% of the time.  Users should instead
   call methods of the trace-based API, e.g., `integrate_trace`.  This is another potential
   source of confusion.

1. **Export API.** The API to export a stream from a nested circuit is verbose and easy to
   get wrong.  First, the user must call `stream.integrate_trace()` inside the circuit to
   sum up all deltas computed across all iterations of the circuit into a trace.  In the
   parent circuit, the user must call `consolidate` to consolidate the trace into a single
   batch.

1. **Recursion API.** Today, a recursive relation is created by manually instantiating a
   `DelayedFeedback` operator and closing the loop using its `.connect()` method.  In addition,
   the user must explicitly apply `distinct` to the recursive relation to ensure convergence.
   This feels verbose and low-level.
   - [x] Proposed solution to this and previous problem: PR #100 

1. **Documentation.**  Once the above issues have been addressed, the resulting API
  needs nice top down documentation with examples.

@absoludity

**Comment by mbudiu-vmw** [comment]
I think an api like the one in the well-formed circuits section is a natural one if it can be built in rust

**Comment by ryzhyk** [comment]
>  I think an api like the one in the well-formed circuits section is a natural one if it can be built in rust

Sorry, I'm not sure what that means.

**Comment by absoludity** [comment]
> > I think an api like the one in the well-formed circuits section is a natural one if it can be built in rust
> 
> Sorry, I'm not sure what that means.

I wasn't sure either, but happened to be browsing the [spec PDF](https://github.com/vmware/database-stream-processor/blob/main/doc/spec.pdf) and guess @mbudiu-vmw is referring to section 9 (Part III, Implementation, Well-formed circuits), though with my limited knowledge at the moment, I'm not sure how the circuit construction rules there (9.4) defines a higher-level API.

**Comment by mbudiu-vmw** [comment]
The api for building acyclic circuits is good. For loops  it would be nice to build the body first like an acyclovir circuit, then bracket it with delta0 and int, and lift it.
